plugins:
  multilingual_enabled:
    default: true
    client: true
  multilingual_require_language_tag:
    type: enum
    default: "non-staff"
    choices:
      - "no"
      - "yes"
      - "non-staff"
  multilingual_tag_translations_enforce_format: false
  multilingual_guest_visible_locales:
    type: list
    default: ar|zh_CN|en|es|fr|ru
    client: true