plugins:
  multilingual_enabled:
    default: false
    client: true
  multilingual_require_language_tag:
    type: enum
    default: "non-staff"
    choices:
      - "no"
      - "yes"
      - "non-staff"
  multilingual_tag_translations_enforce_formatting: true